### PR TITLE
Implemented weighted queues

### PR DESCRIPTION
**Pull request by nickpoorman**
From our conversation here: https://github.com/contribsys/faktory/issues/201

I based this off the Sidekiq implementation where it does a shuffle and then a unique on the result of the shuffle.

### CODE REVIEW

**Comment by mperham** [comment]
I don't really like the API, this does not "feel" clean or idiomatic by first setting a struct field and then calling a method:

```go
mgr.Queues = []string{"critical", "default", "bulk"}
mgr.UseWeightedQueues([]int{3, 2, 1})
```

Ponder it and let me know if you have ideas for a refined API.

**Comment by mperham** [comment]
But to be more positive, thanks for this, it's a great first pass. 👍

**Comment by nickpoorman** [comment]
Yeah I don't love the API either. I was trying to find a way to prevent breaking changes. The alternatives I can think of are:

1. We have a method that set's Queues and QueueWeights in one go.

```go
mgr.QueueWeights([]string{"critical", "default", "bulk"}, []int{3, 2, 1})
```

or it could be a map

```go
mgr.QueueWeights(map[string]int{"critical": 3, "default": 2, "bulk": 1)
```

2. We could have QueueWeights be a property. But this is going to present some challenges with initializing. Maybe on `Run()`?

```go
mgr.Queues = []string{"critical", "default", "bulk"}
mgr.QueueWeights = []int{3, 2, 1}
```

3. We could have an additional constructor for `NewManager` that takes these params.

```go
mgr := worker.NewManager(map[string]int{"critical": 3, "default": 2, "bulk": 1})
```


Theres some breaking changes we could make where Queues would be a type. And then do the initialization on Run.

```go
type Queue struct {
	Name   string
	Weight int
}

mgr.Queues = []Queue{{"critical", 3}, {"default", 2}, {"bulk", 1}}
```

That's all I can think of right now but I'll keep pondering it.

**Comment by mperham** [comment]
I like the idea of `mgr.StrictPriorityQueues("a", "b", c")` and `mgr.WeightedPriorityQueues(map[string]int{...})`. 👍  It lets the user signal their exact intent.

**Comment by mperham** [comment]
How do we document this?  README?

**Comment by mperham** [comment]
I've made some minor changes and added credit for you in the new changelog.  Thanks!

**Comment by mperham** [comment]
The Process methods are meant to be called only once, before Run.

**Pull request merged**
